/********************************************************************************
** Form generated from reading UI file 'mega_fm.ui'
**
** Created by: Qt User Interface Compiler version 5.12.8
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDial>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QGroupBox *groupBox_1;
    QDial *dial_pitch_1;
    QDial *dial_ramp_amount_1;
    QDial *dial_ramp_decay_1;
    QDial *dial_fm_amount_1;
    QDial *dial_fm_freq_1;
    QDial *dial_fm_decay_1;
    QDial *dial_fm_feedback_1;
    QDial *dial_amp_decay_1;
    QDial *dial_volume_1;
    QGroupBox *groupBox_labels;
    QLabel *label_pitch;
    QLabel *label_ramp;
    QLabel *label_ramp_decay;
    QLabel *label_fm_amount;
    QLabel *label_fm_frequency;
    QLabel *label_fm_decay;
    QLabel *label_fm_feedback;
    QLabel *label_aeg;
    QLabel *label_volume;
    QGroupBox *groupBox_4;
    QDial *dial_pitch_4;
    QDial *dial_ramp_amount_4;
    QDial *dial_ramp_decay_4;
    QDial *dial_fm_amount_4;
    QDial *dial_fm_freq_4;
    QDial *dial_fm_decay_4;
    QDial *dial_fm_feedback_4;
    QDial *dial_amp_decay_4;
    QDial *dial_volume_4;
    QGroupBox *groupBox_5;
    QDial *dial_pitch_5;
    QDial *dial_ramp_amount_5;
    QDial *dial_ramp_decay_5;
    QDial *dial_fm_amount_5;
    QDial *dial_5_fm_freq_5;
    QDial *dial_fm_decay_5;
    QDial *dial_fm_feedback_5;
    QDial *dial_amp_decay_5;
    QDial *dial_volume_5;
    QGroupBox *groupBox_6;
    QDial *dial_pitch_6;
    QDial *dial_ramp_amount_6;
    QDial *dial_ramp_decay_6;
    QDial *dial_fm_amount_6;
    QDial *dial_5_fm_freq_6;
    QDial *dial_fm_decay_6;
    QDial *dial_fm_feedback_6;
    QDial *dial_amp_decay_6;
    QDial *dial_volume_6;
    QGroupBox *groupBox_7;
    QDial *dial_pitch_7;
    QDial *dial_ramp_amount_7;
    QDial *dial_ramp_decay_7;
    QDial *dial_fm_amount_7;
    QDial *dial_5_fm_freq_7;
    QDial *dial_fm_decay_7;
    QDial *dial_fm_feedback_7;
    QDial *dial_amp_decay_7;
    QDial *dial_volume_7;
    QGroupBox *groupBox_8;
    QDial *dial_pitch_8;
    QDial *dial_ramp_amount_8;
    QDial *dial_ramp_decay_8;
    QDial *dial_fm_amount_8;
    QDial *dial_5_fm_freq_8;
    QDial *dial_fm_decay_8;
    QDial *dial_fm_feedback_8;
    QDial *dial_amp_decay_8;
    QDial *dial_volume_8;
    QGroupBox *groupBox_9;
    QDial *dial_pitch_9;
    QDial *dial_ramp_amount_9;
    QDial *dial_ramp_decay_9;
    QDial *dial_fm_amount_9;
    QDial *dial_5_fm_freq_9;
    QDial *dial_fm_decay_9;
    QDial *dial_fm_feedback_9;
    QDial *dial_amp_decay_9;
    QDial *dial_volume_9;
    QGroupBox *groupBox_10;
    QDial *dial_pitch_10;
    QDial *dial_ramp_amount_10;
    QDial *dial_ramp_decay_10;
    QDial *dial_fm_amount_10;
    QDial *dial_5_fm_freq_10;
    QDial *dial_fm_decay_10;
    QDial *dial_fm_feedback_10;
    QDial *dial_amp_decay_10;
    QDial *dial_volume_10;
    QGroupBox *groupBox_11;
    QDial *dial_pitch_11;
    QDial *dial_ramp_amount_11;
    QDial *dial_ramp_decay_11;
    QDial *dial_fm_amount_11;
    QDial *dial_5_fm_freq_11;
    QDial *dial_fm_decay_11;
    QDial *dial_fm_feedback_11;
    QDial *dial_amp_decay_11;
    QDial *dial_volume_11;
    QGroupBox *groupBox_12;
    QDial *dial_pitch_12;
    QDial *dial_ramp_amount_12;
    QDial *dial_ramp_decay_12;
    QDial *dial_fm_amount_12;
    QDial *dial_5_fm_freq_12;
    QDial *dial_fm_decay_12;
    QDial *dial_fm_feedback_12;
    QDial *dial_amp_decay_12;
    QDial *dial_volume_12;
    QGroupBox *groupBox_13;
    QDial *dial_pitch_13;
    QDial *dial_ramp_amount_13;
    QDial *dial_ramp_decay_13;
    QDial *dial_fm_amount_13;
    QDial *dial_5_fm_freq_13;
    QDial *dial_fm_decay_13;
    QDial *dial_fm_feedback_13;
    QDial *dial_amp_decay_13;
    QDial *dial_volume_13;
    QGroupBox *groupBox_14;
    QDial *dial_pitch_14;
    QDial *dial_ramp_amount_14;
    QDial *dial_ramp_decay_14;
    QDial *dial_fm_amount_14;
    QDial *dial_5_fm_freq_14;
    QDial *dial_fm_decay_14;
    QDial *dial_fm_feedback_14;
    QDial *dial_amp_decay_14;
    QDial *dial_volume_14;
    QGroupBox *groupBox_15;
    QDial *dial_pitch_15;
    QDial *dial_ramp_amount_15;
    QDial *dial_ramp_decay_15;
    QDial *dial_fm_amount_15;
    QDial *dial_5_fm_freq_17;
    QDial *dial_fm_decay_15;
    QDial *dial_fm_feedback_15;
    QDial *dial_amp_decay_15;
    QDial *dial_volume_15;
    QGroupBox *groupBox_16;
    QDial *dial_pitch_16;
    QDial *dial_ramp_amount_16;
    QDial *dial_ramp_decay_16;
    QDial *dial_fm_amount_16;
    QDial *dial_5_fm_freq_16;
    QDial *dial_fm_decay_16;
    QDial *dial_fm_feedback_16;
    QDial *dial_amp_decay_16;
    QDial *dial_volume_16;
    QGroupBox *groupBox_2;
    QDial *dial_pitch_2;
    QDial *dial_ramp_amount_2;
    QDial *dial_ramp_decay_2;
    QDial *dial_fm_amount_2;
    QDial *dial_fm_freq_2;
    QDial *dial_fm_decay_2;
    QDial *dial_fm_feedback_2;
    QDial *dial_amp_decay_2;
    QDial *dial_volume_2;
    QGroupBox *groupBox_3;
    QDial *dial_pitch_3;
    QDial *dial_ramp_amount_3;
    QDial *dial_ramp_decay_3;
    QDial *dial_fm_amount_3;
    QDial *dial_fm_freq_3;
    QDial *dial_fm_decay_3;
    QDial *dial_fm_feedback_3;
    QDial *dial_amp_decay_3;
    QDial *dial_volume_3;
    QGroupBox *groupBox_master_controls;
    QDial *dial_master_pitch;
    QDial *dial_master_fm_amount;
    QDial *dial_master_volume;
    QDial *dial_master_volume_2;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(842, 691);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        groupBox_1 = new QGroupBox(centralwidget);
        groupBox_1->setObjectName(QString::fromUtf8("groupBox_1"));
        groupBox_1->setGeometry(QRect(140, 130, 41, 441));
        groupBox_1->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_1 = new QDial(groupBox_1);
        dial_pitch_1->setObjectName(QString::fromUtf8("dial_pitch_1"));
        dial_pitch_1->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_1->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_1->setMinimum(-500);
        dial_pitch_1->setMaximum(500);
        dial_ramp_amount_1 = new QDial(groupBox_1);
        dial_ramp_amount_1->setObjectName(QString::fromUtf8("dial_ramp_amount_1"));
        dial_ramp_amount_1->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_1->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_1->setMaximum(1000);
        dial_ramp_decay_1 = new QDial(groupBox_1);
        dial_ramp_decay_1->setObjectName(QString::fromUtf8("dial_ramp_decay_1"));
        dial_ramp_decay_1->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_1->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_1->setMaximum(1000);
        dial_fm_amount_1 = new QDial(groupBox_1);
        dial_fm_amount_1->setObjectName(QString::fromUtf8("dial_fm_amount_1"));
        dial_fm_amount_1->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_1->setAutoFillBackground(false);
        dial_fm_amount_1->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_1->setMaximum(1000);
        dial_fm_freq_1 = new QDial(groupBox_1);
        dial_fm_freq_1->setObjectName(QString::fromUtf8("dial_fm_freq_1"));
        dial_fm_freq_1->setGeometry(QRect(0, 200, 41, 41));
        dial_fm_freq_1->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_freq_1->setMaximum(1000);
        dial_fm_decay_1 = new QDial(groupBox_1);
        dial_fm_decay_1->setObjectName(QString::fromUtf8("dial_fm_decay_1"));
        dial_fm_decay_1->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_1->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_1->setMaximum(1000);
        dial_fm_feedback_1 = new QDial(groupBox_1);
        dial_fm_feedback_1->setObjectName(QString::fromUtf8("dial_fm_feedback_1"));
        dial_fm_feedback_1->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_1->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_1->setMaximum(1000);
        dial_amp_decay_1 = new QDial(groupBox_1);
        dial_amp_decay_1->setObjectName(QString::fromUtf8("dial_amp_decay_1"));
        dial_amp_decay_1->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_1->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_1->setMaximum(1000);
        dial_amp_decay_1->setValue(500);
        dial_volume_1 = new QDial(groupBox_1);
        dial_volume_1->setObjectName(QString::fromUtf8("dial_volume_1"));
        dial_volume_1->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_1->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_1->setMaximum(1000);
        dial_volume_1->setValue(1000);
        groupBox_labels = new QGroupBox(centralwidget);
        groupBox_labels->setObjectName(QString::fromUtf8("groupBox_labels"));
        groupBox_labels->setGeometry(QRect(40, 130, 91, 441));
        groupBox_labels->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        label_pitch = new QLabel(groupBox_labels);
        label_pitch->setObjectName(QString::fromUtf8("label_pitch"));
        label_pitch->setGeometry(QRect(10, 30, 67, 21));
        label_pitch->setStyleSheet(QString::fromUtf8("border: none; background-color:pink;"));
        label_ramp = new QLabel(groupBox_labels);
        label_ramp->setObjectName(QString::fromUtf8("label_ramp"));
        label_ramp->setGeometry(QRect(10, 70, 67, 21));
        label_ramp->setStyleSheet(QString::fromUtf8("border: none; background-color:pink;"));
        label_ramp_decay = new QLabel(groupBox_labels);
        label_ramp_decay->setObjectName(QString::fromUtf8("label_ramp_decay"));
        label_ramp_decay->setGeometry(QRect(10, 110, 67, 21));
        label_ramp_decay->setStyleSheet(QString::fromUtf8("border: none; background-color:pink;"));
        label_fm_amount = new QLabel(groupBox_labels);
        label_fm_amount->setObjectName(QString::fromUtf8("label_fm_amount"));
        label_fm_amount->setGeometry(QRect(10, 170, 67, 21));
        label_fm_amount->setStyleSheet(QString::fromUtf8("border: none; background-color:lightblue;"));
        label_fm_frequency = new QLabel(groupBox_labels);
        label_fm_frequency->setObjectName(QString::fromUtf8("label_fm_frequency"));
        label_fm_frequency->setGeometry(QRect(10, 210, 67, 21));
        label_fm_frequency->setStyleSheet(QString::fromUtf8("border: none; background-color:lightblue;"));
        label_fm_decay = new QLabel(groupBox_labels);
        label_fm_decay->setObjectName(QString::fromUtf8("label_fm_decay"));
        label_fm_decay->setGeometry(QRect(10, 250, 67, 21));
        label_fm_decay->setStyleSheet(QString::fromUtf8("border: none; background-color:lightblue;"));
        label_fm_feedback = new QLabel(groupBox_labels);
        label_fm_feedback->setObjectName(QString::fromUtf8("label_fm_feedback"));
        label_fm_feedback->setGeometry(QRect(10, 290, 67, 21));
        label_fm_feedback->setStyleSheet(QString::fromUtf8("border: none; background-color:lightblue;"));
        label_aeg = new QLabel(groupBox_labels);
        label_aeg->setObjectName(QString::fromUtf8("label_aeg"));
        label_aeg->setGeometry(QRect(10, 340, 67, 21));
        label_aeg->setStyleSheet(QString::fromUtf8("border: none; background-color:lightgray;"));
        label_volume = new QLabel(groupBox_labels);
        label_volume->setObjectName(QString::fromUtf8("label_volume"));
        label_volume->setGeometry(QRect(10, 380, 67, 21));
        label_volume->setStyleSheet(QString::fromUtf8("border: none; background-color:lightgray;"));
        groupBox_4 = new QGroupBox(centralwidget);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(260, 130, 41, 441));
        groupBox_4->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_4 = new QDial(groupBox_4);
        dial_pitch_4->setObjectName(QString::fromUtf8("dial_pitch_4"));
        dial_pitch_4->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_4->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_4->setMinimum(-500);
        dial_pitch_4->setMaximum(500);
        dial_ramp_amount_4 = new QDial(groupBox_4);
        dial_ramp_amount_4->setObjectName(QString::fromUtf8("dial_ramp_amount_4"));
        dial_ramp_amount_4->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_4->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_4->setMaximum(1000);
        dial_ramp_decay_4 = new QDial(groupBox_4);
        dial_ramp_decay_4->setObjectName(QString::fromUtf8("dial_ramp_decay_4"));
        dial_ramp_decay_4->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_4->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_4->setMaximum(1000);
        dial_fm_amount_4 = new QDial(groupBox_4);
        dial_fm_amount_4->setObjectName(QString::fromUtf8("dial_fm_amount_4"));
        dial_fm_amount_4->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_4->setAutoFillBackground(false);
        dial_fm_amount_4->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_4->setMaximum(1000);
        dial_fm_freq_4 = new QDial(groupBox_4);
        dial_fm_freq_4->setObjectName(QString::fromUtf8("dial_fm_freq_4"));
        dial_fm_freq_4->setGeometry(QRect(0, 200, 41, 41));
        dial_fm_freq_4->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_freq_4->setMaximum(1000);
        dial_fm_decay_4 = new QDial(groupBox_4);
        dial_fm_decay_4->setObjectName(QString::fromUtf8("dial_fm_decay_4"));
        dial_fm_decay_4->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_4->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_4->setMaximum(1000);
        dial_fm_feedback_4 = new QDial(groupBox_4);
        dial_fm_feedback_4->setObjectName(QString::fromUtf8("dial_fm_feedback_4"));
        dial_fm_feedback_4->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_4->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_4->setMaximum(1000);
        dial_amp_decay_4 = new QDial(groupBox_4);
        dial_amp_decay_4->setObjectName(QString::fromUtf8("dial_amp_decay_4"));
        dial_amp_decay_4->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_4->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_4->setMaximum(1000);
        dial_amp_decay_4->setValue(500);
        dial_volume_4 = new QDial(groupBox_4);
        dial_volume_4->setObjectName(QString::fromUtf8("dial_volume_4"));
        dial_volume_4->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_4->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_4->setMaximum(1000);
        dial_volume_4->setValue(1000);
        groupBox_5 = new QGroupBox(centralwidget);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(310, 130, 41, 441));
        groupBox_5->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_5 = new QDial(groupBox_5);
        dial_pitch_5->setObjectName(QString::fromUtf8("dial_pitch_5"));
        dial_pitch_5->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_5->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_5->setMinimum(-500);
        dial_pitch_5->setMaximum(500);
        dial_ramp_amount_5 = new QDial(groupBox_5);
        dial_ramp_amount_5->setObjectName(QString::fromUtf8("dial_ramp_amount_5"));
        dial_ramp_amount_5->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_5->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_5->setMaximum(1000);
        dial_ramp_decay_5 = new QDial(groupBox_5);
        dial_ramp_decay_5->setObjectName(QString::fromUtf8("dial_ramp_decay_5"));
        dial_ramp_decay_5->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_5->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_5->setMaximum(1000);
        dial_fm_amount_5 = new QDial(groupBox_5);
        dial_fm_amount_5->setObjectName(QString::fromUtf8("dial_fm_amount_5"));
        dial_fm_amount_5->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_5->setAutoFillBackground(false);
        dial_fm_amount_5->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_5->setMaximum(1000);
        dial_5_fm_freq_5 = new QDial(groupBox_5);
        dial_5_fm_freq_5->setObjectName(QString::fromUtf8("dial_5_fm_freq_5"));
        dial_5_fm_freq_5->setGeometry(QRect(0, 200, 41, 41));
        dial_5_fm_freq_5->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_5_fm_freq_5->setMaximum(1000);
        dial_fm_decay_5 = new QDial(groupBox_5);
        dial_fm_decay_5->setObjectName(QString::fromUtf8("dial_fm_decay_5"));
        dial_fm_decay_5->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_5->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_5->setMaximum(1000);
        dial_fm_feedback_5 = new QDial(groupBox_5);
        dial_fm_feedback_5->setObjectName(QString::fromUtf8("dial_fm_feedback_5"));
        dial_fm_feedback_5->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_5->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_5->setMaximum(1000);
        dial_amp_decay_5 = new QDial(groupBox_5);
        dial_amp_decay_5->setObjectName(QString::fromUtf8("dial_amp_decay_5"));
        dial_amp_decay_5->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_5->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_5->setMaximum(1000);
        dial_amp_decay_5->setValue(500);
        dial_volume_5 = new QDial(groupBox_5);
        dial_volume_5->setObjectName(QString::fromUtf8("dial_volume_5"));
        dial_volume_5->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_5->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_5->setMaximum(1000);
        dial_volume_5->setValue(1000);
        groupBox_6 = new QGroupBox(centralwidget);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(350, 130, 41, 441));
        groupBox_6->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_6 = new QDial(groupBox_6);
        dial_pitch_6->setObjectName(QString::fromUtf8("dial_pitch_6"));
        dial_pitch_6->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_6->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_6->setMinimum(-500);
        dial_pitch_6->setMaximum(500);
        dial_ramp_amount_6 = new QDial(groupBox_6);
        dial_ramp_amount_6->setObjectName(QString::fromUtf8("dial_ramp_amount_6"));
        dial_ramp_amount_6->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_6->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_6->setMaximum(1000);
        dial_ramp_decay_6 = new QDial(groupBox_6);
        dial_ramp_decay_6->setObjectName(QString::fromUtf8("dial_ramp_decay_6"));
        dial_ramp_decay_6->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_6->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_6->setMaximum(1000);
        dial_fm_amount_6 = new QDial(groupBox_6);
        dial_fm_amount_6->setObjectName(QString::fromUtf8("dial_fm_amount_6"));
        dial_fm_amount_6->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_6->setAutoFillBackground(false);
        dial_fm_amount_6->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_6->setMaximum(1000);
        dial_5_fm_freq_6 = new QDial(groupBox_6);
        dial_5_fm_freq_6->setObjectName(QString::fromUtf8("dial_5_fm_freq_6"));
        dial_5_fm_freq_6->setGeometry(QRect(0, 200, 41, 41));
        dial_5_fm_freq_6->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_5_fm_freq_6->setMaximum(1000);
        dial_fm_decay_6 = new QDial(groupBox_6);
        dial_fm_decay_6->setObjectName(QString::fromUtf8("dial_fm_decay_6"));
        dial_fm_decay_6->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_6->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_6->setMaximum(1000);
        dial_fm_feedback_6 = new QDial(groupBox_6);
        dial_fm_feedback_6->setObjectName(QString::fromUtf8("dial_fm_feedback_6"));
        dial_fm_feedback_6->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_6->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_6->setMaximum(1000);
        dial_amp_decay_6 = new QDial(groupBox_6);
        dial_amp_decay_6->setObjectName(QString::fromUtf8("dial_amp_decay_6"));
        dial_amp_decay_6->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_6->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_6->setMaximum(1000);
        dial_amp_decay_6->setValue(500);
        dial_volume_6 = new QDial(groupBox_6);
        dial_volume_6->setObjectName(QString::fromUtf8("dial_volume_6"));
        dial_volume_6->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_6->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_6->setMaximum(1000);
        dial_volume_6->setValue(1000);
        groupBox_7 = new QGroupBox(centralwidget);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(390, 130, 41, 441));
        groupBox_7->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_7 = new QDial(groupBox_7);
        dial_pitch_7->setObjectName(QString::fromUtf8("dial_pitch_7"));
        dial_pitch_7->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_7->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_7->setMinimum(-500);
        dial_pitch_7->setMaximum(500);
        dial_ramp_amount_7 = new QDial(groupBox_7);
        dial_ramp_amount_7->setObjectName(QString::fromUtf8("dial_ramp_amount_7"));
        dial_ramp_amount_7->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_7->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_7->setMaximum(1000);
        dial_ramp_decay_7 = new QDial(groupBox_7);
        dial_ramp_decay_7->setObjectName(QString::fromUtf8("dial_ramp_decay_7"));
        dial_ramp_decay_7->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_7->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_7->setMaximum(1000);
        dial_fm_amount_7 = new QDial(groupBox_7);
        dial_fm_amount_7->setObjectName(QString::fromUtf8("dial_fm_amount_7"));
        dial_fm_amount_7->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_7->setAutoFillBackground(false);
        dial_fm_amount_7->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_7->setMaximum(1000);
        dial_5_fm_freq_7 = new QDial(groupBox_7);
        dial_5_fm_freq_7->setObjectName(QString::fromUtf8("dial_5_fm_freq_7"));
        dial_5_fm_freq_7->setGeometry(QRect(0, 200, 41, 41));
        dial_5_fm_freq_7->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_5_fm_freq_7->setMaximum(1000);
        dial_fm_decay_7 = new QDial(groupBox_7);
        dial_fm_decay_7->setObjectName(QString::fromUtf8("dial_fm_decay_7"));
        dial_fm_decay_7->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_7->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_7->setMaximum(1000);
        dial_fm_feedback_7 = new QDial(groupBox_7);
        dial_fm_feedback_7->setObjectName(QString::fromUtf8("dial_fm_feedback_7"));
        dial_fm_feedback_7->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_7->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_7->setMaximum(1000);
        dial_amp_decay_7 = new QDial(groupBox_7);
        dial_amp_decay_7->setObjectName(QString::fromUtf8("dial_amp_decay_7"));
        dial_amp_decay_7->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_7->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_7->setMaximum(1000);
        dial_amp_decay_7->setValue(500);
        dial_volume_7 = new QDial(groupBox_7);
        dial_volume_7->setObjectName(QString::fromUtf8("dial_volume_7"));
        dial_volume_7->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_7->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_7->setMaximum(1000);
        dial_volume_7->setValue(1000);
        groupBox_8 = new QGroupBox(centralwidget);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(430, 130, 41, 441));
        groupBox_8->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_8 = new QDial(groupBox_8);
        dial_pitch_8->setObjectName(QString::fromUtf8("dial_pitch_8"));
        dial_pitch_8->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_8->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_8->setMinimum(-500);
        dial_pitch_8->setMaximum(500);
        dial_ramp_amount_8 = new QDial(groupBox_8);
        dial_ramp_amount_8->setObjectName(QString::fromUtf8("dial_ramp_amount_8"));
        dial_ramp_amount_8->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_8->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_8->setMaximum(1000);
        dial_ramp_decay_8 = new QDial(groupBox_8);
        dial_ramp_decay_8->setObjectName(QString::fromUtf8("dial_ramp_decay_8"));
        dial_ramp_decay_8->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_8->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_8->setMaximum(1000);
        dial_fm_amount_8 = new QDial(groupBox_8);
        dial_fm_amount_8->setObjectName(QString::fromUtf8("dial_fm_amount_8"));
        dial_fm_amount_8->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_8->setAutoFillBackground(false);
        dial_fm_amount_8->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_8->setMaximum(1000);
        dial_5_fm_freq_8 = new QDial(groupBox_8);
        dial_5_fm_freq_8->setObjectName(QString::fromUtf8("dial_5_fm_freq_8"));
        dial_5_fm_freq_8->setGeometry(QRect(0, 200, 41, 41));
        dial_5_fm_freq_8->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_5_fm_freq_8->setMaximum(1000);
        dial_fm_decay_8 = new QDial(groupBox_8);
        dial_fm_decay_8->setObjectName(QString::fromUtf8("dial_fm_decay_8"));
        dial_fm_decay_8->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_8->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_8->setMaximum(1000);
        dial_fm_feedback_8 = new QDial(groupBox_8);
        dial_fm_feedback_8->setObjectName(QString::fromUtf8("dial_fm_feedback_8"));
        dial_fm_feedback_8->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_8->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_8->setMaximum(1000);
        dial_amp_decay_8 = new QDial(groupBox_8);
        dial_amp_decay_8->setObjectName(QString::fromUtf8("dial_amp_decay_8"));
        dial_amp_decay_8->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_8->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_8->setMaximum(1000);
        dial_amp_decay_8->setValue(500);
        dial_volume_8 = new QDial(groupBox_8);
        dial_volume_8->setObjectName(QString::fromUtf8("dial_volume_8"));
        dial_volume_8->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_8->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_8->setMaximum(1000);
        dial_volume_8->setValue(1000);
        groupBox_9 = new QGroupBox(centralwidget);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(480, 130, 41, 441));
        groupBox_9->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_9 = new QDial(groupBox_9);
        dial_pitch_9->setObjectName(QString::fromUtf8("dial_pitch_9"));
        dial_pitch_9->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_9->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_9->setMinimum(-500);
        dial_pitch_9->setMaximum(500);
        dial_ramp_amount_9 = new QDial(groupBox_9);
        dial_ramp_amount_9->setObjectName(QString::fromUtf8("dial_ramp_amount_9"));
        dial_ramp_amount_9->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_9->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_9->setMaximum(1000);
        dial_ramp_decay_9 = new QDial(groupBox_9);
        dial_ramp_decay_9->setObjectName(QString::fromUtf8("dial_ramp_decay_9"));
        dial_ramp_decay_9->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_9->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_9->setMaximum(1000);
        dial_fm_amount_9 = new QDial(groupBox_9);
        dial_fm_amount_9->setObjectName(QString::fromUtf8("dial_fm_amount_9"));
        dial_fm_amount_9->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_9->setAutoFillBackground(false);
        dial_fm_amount_9->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_9->setMaximum(1000);
        dial_5_fm_freq_9 = new QDial(groupBox_9);
        dial_5_fm_freq_9->setObjectName(QString::fromUtf8("dial_5_fm_freq_9"));
        dial_5_fm_freq_9->setGeometry(QRect(0, 200, 41, 41));
        dial_5_fm_freq_9->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_5_fm_freq_9->setMaximum(1000);
        dial_fm_decay_9 = new QDial(groupBox_9);
        dial_fm_decay_9->setObjectName(QString::fromUtf8("dial_fm_decay_9"));
        dial_fm_decay_9->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_9->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_9->setMaximum(1000);
        dial_fm_feedback_9 = new QDial(groupBox_9);
        dial_fm_feedback_9->setObjectName(QString::fromUtf8("dial_fm_feedback_9"));
        dial_fm_feedback_9->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_9->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_9->setMaximum(1000);
        dial_amp_decay_9 = new QDial(groupBox_9);
        dial_amp_decay_9->setObjectName(QString::fromUtf8("dial_amp_decay_9"));
        dial_amp_decay_9->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_9->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_9->setMaximum(1000);
        dial_amp_decay_9->setValue(500);
        dial_volume_9 = new QDial(groupBox_9);
        dial_volume_9->setObjectName(QString::fromUtf8("dial_volume_9"));
        dial_volume_9->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_9->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_9->setMaximum(1000);
        dial_volume_9->setValue(1000);
        groupBox_10 = new QGroupBox(centralwidget);
        groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
        groupBox_10->setGeometry(QRect(520, 130, 41, 441));
        groupBox_10->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_10 = new QDial(groupBox_10);
        dial_pitch_10->setObjectName(QString::fromUtf8("dial_pitch_10"));
        dial_pitch_10->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_10->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_10->setMinimum(-500);
        dial_pitch_10->setMaximum(500);
        dial_ramp_amount_10 = new QDial(groupBox_10);
        dial_ramp_amount_10->setObjectName(QString::fromUtf8("dial_ramp_amount_10"));
        dial_ramp_amount_10->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_10->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_10->setMaximum(1000);
        dial_ramp_decay_10 = new QDial(groupBox_10);
        dial_ramp_decay_10->setObjectName(QString::fromUtf8("dial_ramp_decay_10"));
        dial_ramp_decay_10->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_10->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_10->setMaximum(1000);
        dial_fm_amount_10 = new QDial(groupBox_10);
        dial_fm_amount_10->setObjectName(QString::fromUtf8("dial_fm_amount_10"));
        dial_fm_amount_10->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_10->setAutoFillBackground(false);
        dial_fm_amount_10->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_10->setMaximum(1000);
        dial_5_fm_freq_10 = new QDial(groupBox_10);
        dial_5_fm_freq_10->setObjectName(QString::fromUtf8("dial_5_fm_freq_10"));
        dial_5_fm_freq_10->setGeometry(QRect(0, 200, 41, 41));
        dial_5_fm_freq_10->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_5_fm_freq_10->setMaximum(1000);
        dial_fm_decay_10 = new QDial(groupBox_10);
        dial_fm_decay_10->setObjectName(QString::fromUtf8("dial_fm_decay_10"));
        dial_fm_decay_10->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_10->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_10->setMaximum(1000);
        dial_fm_feedback_10 = new QDial(groupBox_10);
        dial_fm_feedback_10->setObjectName(QString::fromUtf8("dial_fm_feedback_10"));
        dial_fm_feedback_10->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_10->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_10->setMaximum(1000);
        dial_amp_decay_10 = new QDial(groupBox_10);
        dial_amp_decay_10->setObjectName(QString::fromUtf8("dial_amp_decay_10"));
        dial_amp_decay_10->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_10->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_10->setMaximum(1000);
        dial_amp_decay_10->setValue(500);
        dial_volume_10 = new QDial(groupBox_10);
        dial_volume_10->setObjectName(QString::fromUtf8("dial_volume_10"));
        dial_volume_10->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_10->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_10->setMaximum(1000);
        dial_volume_10->setValue(1000);
        groupBox_11 = new QGroupBox(centralwidget);
        groupBox_11->setObjectName(QString::fromUtf8("groupBox_11"));
        groupBox_11->setGeometry(QRect(560, 130, 41, 441));
        groupBox_11->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_11 = new QDial(groupBox_11);
        dial_pitch_11->setObjectName(QString::fromUtf8("dial_pitch_11"));
        dial_pitch_11->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_11->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_11->setMinimum(-500);
        dial_pitch_11->setMaximum(500);
        dial_ramp_amount_11 = new QDial(groupBox_11);
        dial_ramp_amount_11->setObjectName(QString::fromUtf8("dial_ramp_amount_11"));
        dial_ramp_amount_11->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_11->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_11->setMaximum(1000);
        dial_ramp_decay_11 = new QDial(groupBox_11);
        dial_ramp_decay_11->setObjectName(QString::fromUtf8("dial_ramp_decay_11"));
        dial_ramp_decay_11->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_11->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_11->setMaximum(1000);
        dial_fm_amount_11 = new QDial(groupBox_11);
        dial_fm_amount_11->setObjectName(QString::fromUtf8("dial_fm_amount_11"));
        dial_fm_amount_11->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_11->setAutoFillBackground(false);
        dial_fm_amount_11->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_11->setMaximum(1000);
        dial_5_fm_freq_11 = new QDial(groupBox_11);
        dial_5_fm_freq_11->setObjectName(QString::fromUtf8("dial_5_fm_freq_11"));
        dial_5_fm_freq_11->setGeometry(QRect(0, 200, 41, 41));
        dial_5_fm_freq_11->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_5_fm_freq_11->setMaximum(1000);
        dial_fm_decay_11 = new QDial(groupBox_11);
        dial_fm_decay_11->setObjectName(QString::fromUtf8("dial_fm_decay_11"));
        dial_fm_decay_11->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_11->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_11->setMaximum(1000);
        dial_fm_feedback_11 = new QDial(groupBox_11);
        dial_fm_feedback_11->setObjectName(QString::fromUtf8("dial_fm_feedback_11"));
        dial_fm_feedback_11->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_11->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_11->setMaximum(1000);
        dial_amp_decay_11 = new QDial(groupBox_11);
        dial_amp_decay_11->setObjectName(QString::fromUtf8("dial_amp_decay_11"));
        dial_amp_decay_11->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_11->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_11->setMaximum(1000);
        dial_amp_decay_11->setValue(500);
        dial_volume_11 = new QDial(groupBox_11);
        dial_volume_11->setObjectName(QString::fromUtf8("dial_volume_11"));
        dial_volume_11->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_11->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_11->setMaximum(1000);
        dial_volume_11->setValue(1000);
        groupBox_12 = new QGroupBox(centralwidget);
        groupBox_12->setObjectName(QString::fromUtf8("groupBox_12"));
        groupBox_12->setGeometry(QRect(600, 130, 41, 441));
        groupBox_12->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_12 = new QDial(groupBox_12);
        dial_pitch_12->setObjectName(QString::fromUtf8("dial_pitch_12"));
        dial_pitch_12->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_12->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_12->setMinimum(-500);
        dial_pitch_12->setMaximum(500);
        dial_ramp_amount_12 = new QDial(groupBox_12);
        dial_ramp_amount_12->setObjectName(QString::fromUtf8("dial_ramp_amount_12"));
        dial_ramp_amount_12->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_12->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_12->setMaximum(1000);
        dial_ramp_decay_12 = new QDial(groupBox_12);
        dial_ramp_decay_12->setObjectName(QString::fromUtf8("dial_ramp_decay_12"));
        dial_ramp_decay_12->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_12->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_12->setMaximum(1000);
        dial_fm_amount_12 = new QDial(groupBox_12);
        dial_fm_amount_12->setObjectName(QString::fromUtf8("dial_fm_amount_12"));
        dial_fm_amount_12->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_12->setAutoFillBackground(false);
        dial_fm_amount_12->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_12->setMaximum(1000);
        dial_5_fm_freq_12 = new QDial(groupBox_12);
        dial_5_fm_freq_12->setObjectName(QString::fromUtf8("dial_5_fm_freq_12"));
        dial_5_fm_freq_12->setGeometry(QRect(0, 200, 41, 41));
        dial_5_fm_freq_12->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_5_fm_freq_12->setMaximum(1000);
        dial_fm_decay_12 = new QDial(groupBox_12);
        dial_fm_decay_12->setObjectName(QString::fromUtf8("dial_fm_decay_12"));
        dial_fm_decay_12->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_12->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_12->setMaximum(1000);
        dial_fm_feedback_12 = new QDial(groupBox_12);
        dial_fm_feedback_12->setObjectName(QString::fromUtf8("dial_fm_feedback_12"));
        dial_fm_feedback_12->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_12->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_12->setMaximum(1000);
        dial_amp_decay_12 = new QDial(groupBox_12);
        dial_amp_decay_12->setObjectName(QString::fromUtf8("dial_amp_decay_12"));
        dial_amp_decay_12->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_12->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_12->setMaximum(1000);
        dial_amp_decay_12->setValue(500);
        dial_volume_12 = new QDial(groupBox_12);
        dial_volume_12->setObjectName(QString::fromUtf8("dial_volume_12"));
        dial_volume_12->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_12->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_12->setMaximum(1000);
        dial_volume_12->setValue(1000);
        groupBox_13 = new QGroupBox(centralwidget);
        groupBox_13->setObjectName(QString::fromUtf8("groupBox_13"));
        groupBox_13->setGeometry(QRect(650, 130, 41, 441));
        groupBox_13->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_13 = new QDial(groupBox_13);
        dial_pitch_13->setObjectName(QString::fromUtf8("dial_pitch_13"));
        dial_pitch_13->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_13->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_13->setMinimum(-500);
        dial_pitch_13->setMaximum(500);
        dial_ramp_amount_13 = new QDial(groupBox_13);
        dial_ramp_amount_13->setObjectName(QString::fromUtf8("dial_ramp_amount_13"));
        dial_ramp_amount_13->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_13->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_13->setMaximum(1000);
        dial_ramp_decay_13 = new QDial(groupBox_13);
        dial_ramp_decay_13->setObjectName(QString::fromUtf8("dial_ramp_decay_13"));
        dial_ramp_decay_13->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_13->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_13->setMaximum(1000);
        dial_fm_amount_13 = new QDial(groupBox_13);
        dial_fm_amount_13->setObjectName(QString::fromUtf8("dial_fm_amount_13"));
        dial_fm_amount_13->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_13->setAutoFillBackground(false);
        dial_fm_amount_13->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_13->setMaximum(1000);
        dial_5_fm_freq_13 = new QDial(groupBox_13);
        dial_5_fm_freq_13->setObjectName(QString::fromUtf8("dial_5_fm_freq_13"));
        dial_5_fm_freq_13->setGeometry(QRect(0, 200, 41, 41));
        dial_5_fm_freq_13->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_5_fm_freq_13->setMaximum(1000);
        dial_fm_decay_13 = new QDial(groupBox_13);
        dial_fm_decay_13->setObjectName(QString::fromUtf8("dial_fm_decay_13"));
        dial_fm_decay_13->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_13->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_13->setMaximum(1000);
        dial_fm_feedback_13 = new QDial(groupBox_13);
        dial_fm_feedback_13->setObjectName(QString::fromUtf8("dial_fm_feedback_13"));
        dial_fm_feedback_13->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_13->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_13->setMaximum(1000);
        dial_amp_decay_13 = new QDial(groupBox_13);
        dial_amp_decay_13->setObjectName(QString::fromUtf8("dial_amp_decay_13"));
        dial_amp_decay_13->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_13->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_13->setMaximum(1000);
        dial_amp_decay_13->setValue(500);
        dial_volume_13 = new QDial(groupBox_13);
        dial_volume_13->setObjectName(QString::fromUtf8("dial_volume_13"));
        dial_volume_13->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_13->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_13->setMaximum(1000);
        dial_volume_13->setValue(1000);
        groupBox_14 = new QGroupBox(centralwidget);
        groupBox_14->setObjectName(QString::fromUtf8("groupBox_14"));
        groupBox_14->setGeometry(QRect(690, 130, 41, 441));
        groupBox_14->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_14 = new QDial(groupBox_14);
        dial_pitch_14->setObjectName(QString::fromUtf8("dial_pitch_14"));
        dial_pitch_14->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_14->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_14->setMinimum(-500);
        dial_pitch_14->setMaximum(500);
        dial_ramp_amount_14 = new QDial(groupBox_14);
        dial_ramp_amount_14->setObjectName(QString::fromUtf8("dial_ramp_amount_14"));
        dial_ramp_amount_14->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_14->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_14->setMaximum(1000);
        dial_ramp_decay_14 = new QDial(groupBox_14);
        dial_ramp_decay_14->setObjectName(QString::fromUtf8("dial_ramp_decay_14"));
        dial_ramp_decay_14->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_14->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_14->setMaximum(1000);
        dial_fm_amount_14 = new QDial(groupBox_14);
        dial_fm_amount_14->setObjectName(QString::fromUtf8("dial_fm_amount_14"));
        dial_fm_amount_14->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_14->setAutoFillBackground(false);
        dial_fm_amount_14->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_14->setMaximum(1000);
        dial_5_fm_freq_14 = new QDial(groupBox_14);
        dial_5_fm_freq_14->setObjectName(QString::fromUtf8("dial_5_fm_freq_14"));
        dial_5_fm_freq_14->setGeometry(QRect(0, 200, 41, 41));
        dial_5_fm_freq_14->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_5_fm_freq_14->setMaximum(1000);
        dial_fm_decay_14 = new QDial(groupBox_14);
        dial_fm_decay_14->setObjectName(QString::fromUtf8("dial_fm_decay_14"));
        dial_fm_decay_14->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_14->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_14->setMaximum(1000);
        dial_fm_feedback_14 = new QDial(groupBox_14);
        dial_fm_feedback_14->setObjectName(QString::fromUtf8("dial_fm_feedback_14"));
        dial_fm_feedback_14->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_14->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_14->setMaximum(1000);
        dial_amp_decay_14 = new QDial(groupBox_14);
        dial_amp_decay_14->setObjectName(QString::fromUtf8("dial_amp_decay_14"));
        dial_amp_decay_14->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_14->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_14->setMaximum(1000);
        dial_amp_decay_14->setValue(500);
        dial_volume_14 = new QDial(groupBox_14);
        dial_volume_14->setObjectName(QString::fromUtf8("dial_volume_14"));
        dial_volume_14->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_14->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_14->setMaximum(1000);
        dial_volume_14->setValue(1000);
        groupBox_15 = new QGroupBox(centralwidget);
        groupBox_15->setObjectName(QString::fromUtf8("groupBox_15"));
        groupBox_15->setGeometry(QRect(730, 130, 41, 441));
        groupBox_15->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_15 = new QDial(groupBox_15);
        dial_pitch_15->setObjectName(QString::fromUtf8("dial_pitch_15"));
        dial_pitch_15->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_15->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_15->setMinimum(-500);
        dial_pitch_15->setMaximum(500);
        dial_ramp_amount_15 = new QDial(groupBox_15);
        dial_ramp_amount_15->setObjectName(QString::fromUtf8("dial_ramp_amount_15"));
        dial_ramp_amount_15->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_15->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_15->setMaximum(1000);
        dial_ramp_decay_15 = new QDial(groupBox_15);
        dial_ramp_decay_15->setObjectName(QString::fromUtf8("dial_ramp_decay_15"));
        dial_ramp_decay_15->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_15->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_15->setMaximum(1000);
        dial_fm_amount_15 = new QDial(groupBox_15);
        dial_fm_amount_15->setObjectName(QString::fromUtf8("dial_fm_amount_15"));
        dial_fm_amount_15->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_15->setAutoFillBackground(false);
        dial_fm_amount_15->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_15->setMaximum(1000);
        dial_5_fm_freq_17 = new QDial(groupBox_15);
        dial_5_fm_freq_17->setObjectName(QString::fromUtf8("dial_5_fm_freq_17"));
        dial_5_fm_freq_17->setGeometry(QRect(0, 200, 41, 41));
        dial_5_fm_freq_17->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_5_fm_freq_17->setMaximum(1000);
        dial_fm_decay_15 = new QDial(groupBox_15);
        dial_fm_decay_15->setObjectName(QString::fromUtf8("dial_fm_decay_15"));
        dial_fm_decay_15->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_15->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_15->setMaximum(1000);
        dial_fm_feedback_15 = new QDial(groupBox_15);
        dial_fm_feedback_15->setObjectName(QString::fromUtf8("dial_fm_feedback_15"));
        dial_fm_feedback_15->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_15->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_15->setMaximum(1000);
        dial_amp_decay_15 = new QDial(groupBox_15);
        dial_amp_decay_15->setObjectName(QString::fromUtf8("dial_amp_decay_15"));
        dial_amp_decay_15->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_15->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_15->setMaximum(1000);
        dial_amp_decay_15->setValue(500);
        dial_volume_15 = new QDial(groupBox_15);
        dial_volume_15->setObjectName(QString::fromUtf8("dial_volume_15"));
        dial_volume_15->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_15->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_15->setMaximum(1000);
        dial_volume_15->setValue(1000);
        groupBox_16 = new QGroupBox(centralwidget);
        groupBox_16->setObjectName(QString::fromUtf8("groupBox_16"));
        groupBox_16->setGeometry(QRect(770, 130, 41, 441));
        groupBox_16->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_16 = new QDial(groupBox_16);
        dial_pitch_16->setObjectName(QString::fromUtf8("dial_pitch_16"));
        dial_pitch_16->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_16->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_16->setMinimum(-500);
        dial_pitch_16->setMaximum(500);
        dial_ramp_amount_16 = new QDial(groupBox_16);
        dial_ramp_amount_16->setObjectName(QString::fromUtf8("dial_ramp_amount_16"));
        dial_ramp_amount_16->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_16->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_16->setMaximum(1000);
        dial_ramp_decay_16 = new QDial(groupBox_16);
        dial_ramp_decay_16->setObjectName(QString::fromUtf8("dial_ramp_decay_16"));
        dial_ramp_decay_16->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_16->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_16->setMaximum(1000);
        dial_fm_amount_16 = new QDial(groupBox_16);
        dial_fm_amount_16->setObjectName(QString::fromUtf8("dial_fm_amount_16"));
        dial_fm_amount_16->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_16->setAutoFillBackground(false);
        dial_fm_amount_16->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_16->setMaximum(1000);
        dial_5_fm_freq_16 = new QDial(groupBox_16);
        dial_5_fm_freq_16->setObjectName(QString::fromUtf8("dial_5_fm_freq_16"));
        dial_5_fm_freq_16->setGeometry(QRect(0, 200, 41, 41));
        dial_5_fm_freq_16->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_5_fm_freq_16->setMaximum(1000);
        dial_fm_decay_16 = new QDial(groupBox_16);
        dial_fm_decay_16->setObjectName(QString::fromUtf8("dial_fm_decay_16"));
        dial_fm_decay_16->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_16->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_16->setMaximum(1000);
        dial_fm_feedback_16 = new QDial(groupBox_16);
        dial_fm_feedback_16->setObjectName(QString::fromUtf8("dial_fm_feedback_16"));
        dial_fm_feedback_16->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_16->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_16->setMaximum(1000);
        dial_amp_decay_16 = new QDial(groupBox_16);
        dial_amp_decay_16->setObjectName(QString::fromUtf8("dial_amp_decay_16"));
        dial_amp_decay_16->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_16->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_16->setMaximum(1000);
        dial_amp_decay_16->setValue(500);
        dial_volume_16 = new QDial(groupBox_16);
        dial_volume_16->setObjectName(QString::fromUtf8("dial_volume_16"));
        dial_volume_16->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_16->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_16->setMaximum(1000);
        dial_volume_16->setValue(1000);
        groupBox_2 = new QGroupBox(centralwidget);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(180, 130, 41, 441));
        groupBox_2->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_2 = new QDial(groupBox_2);
        dial_pitch_2->setObjectName(QString::fromUtf8("dial_pitch_2"));
        dial_pitch_2->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_2->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_2->setMinimum(-500);
        dial_pitch_2->setMaximum(500);
        dial_ramp_amount_2 = new QDial(groupBox_2);
        dial_ramp_amount_2->setObjectName(QString::fromUtf8("dial_ramp_amount_2"));
        dial_ramp_amount_2->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_2->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_2->setMaximum(1000);
        dial_ramp_decay_2 = new QDial(groupBox_2);
        dial_ramp_decay_2->setObjectName(QString::fromUtf8("dial_ramp_decay_2"));
        dial_ramp_decay_2->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_2->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_2->setMaximum(1000);
        dial_fm_amount_2 = new QDial(groupBox_2);
        dial_fm_amount_2->setObjectName(QString::fromUtf8("dial_fm_amount_2"));
        dial_fm_amount_2->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_2->setAutoFillBackground(false);
        dial_fm_amount_2->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_2->setMaximum(1000);
        dial_fm_freq_2 = new QDial(groupBox_2);
        dial_fm_freq_2->setObjectName(QString::fromUtf8("dial_fm_freq_2"));
        dial_fm_freq_2->setGeometry(QRect(0, 200, 41, 41));
        dial_fm_freq_2->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_freq_2->setMaximum(1000);
        dial_fm_decay_2 = new QDial(groupBox_2);
        dial_fm_decay_2->setObjectName(QString::fromUtf8("dial_fm_decay_2"));
        dial_fm_decay_2->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_2->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_2->setMaximum(1000);
        dial_fm_feedback_2 = new QDial(groupBox_2);
        dial_fm_feedback_2->setObjectName(QString::fromUtf8("dial_fm_feedback_2"));
        dial_fm_feedback_2->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_2->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_2->setMaximum(1000);
        dial_amp_decay_2 = new QDial(groupBox_2);
        dial_amp_decay_2->setObjectName(QString::fromUtf8("dial_amp_decay_2"));
        dial_amp_decay_2->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_2->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_2->setMaximum(1000);
        dial_amp_decay_2->setValue(500);
        dial_volume_2 = new QDial(groupBox_2);
        dial_volume_2->setObjectName(QString::fromUtf8("dial_volume_2"));
        dial_volume_2->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_2->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_2->setMaximum(1000);
        dial_volume_2->setValue(1000);
        groupBox_3 = new QGroupBox(centralwidget);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(220, 130, 41, 441));
        groupBox_3->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_3 = new QDial(groupBox_3);
        dial_pitch_3->setObjectName(QString::fromUtf8("dial_pitch_3"));
        dial_pitch_3->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_3->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_pitch_3->setMinimum(-500);
        dial_pitch_3->setMaximum(500);
        dial_ramp_amount_3 = new QDial(groupBox_3);
        dial_ramp_amount_3->setObjectName(QString::fromUtf8("dial_ramp_amount_3"));
        dial_ramp_amount_3->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_3->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_amount_3->setMaximum(1000);
        dial_ramp_decay_3 = new QDial(groupBox_3);
        dial_ramp_decay_3->setObjectName(QString::fromUtf8("dial_ramp_decay_3"));
        dial_ramp_decay_3->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_3->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_ramp_decay_3->setMaximum(1000);
        dial_fm_amount_3 = new QDial(groupBox_3);
        dial_fm_amount_3->setObjectName(QString::fromUtf8("dial_fm_amount_3"));
        dial_fm_amount_3->setGeometry(QRect(0, 160, 41, 41));
        dial_fm_amount_3->setAutoFillBackground(false);
        dial_fm_amount_3->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_amount_3->setMaximum(1000);
        dial_fm_freq_3 = new QDial(groupBox_3);
        dial_fm_freq_3->setObjectName(QString::fromUtf8("dial_fm_freq_3"));
        dial_fm_freq_3->setGeometry(QRect(0, 200, 41, 41));
        dial_fm_freq_3->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_freq_3->setMaximum(1000);
        dial_fm_decay_3 = new QDial(groupBox_3);
        dial_fm_decay_3->setObjectName(QString::fromUtf8("dial_fm_decay_3"));
        dial_fm_decay_3->setGeometry(QRect(0, 240, 41, 41));
        dial_fm_decay_3->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_decay_3->setMaximum(1000);
        dial_fm_feedback_3 = new QDial(groupBox_3);
        dial_fm_feedback_3->setObjectName(QString::fromUtf8("dial_fm_feedback_3"));
        dial_fm_feedback_3->setGeometry(QRect(0, 280, 41, 41));
        dial_fm_feedback_3->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_fm_feedback_3->setMaximum(1000);
        dial_amp_decay_3 = new QDial(groupBox_3);
        dial_amp_decay_3->setObjectName(QString::fromUtf8("dial_amp_decay_3"));
        dial_amp_decay_3->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_3->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_3->setMaximum(1000);
        dial_amp_decay_3->setValue(500);
        dial_volume_3 = new QDial(groupBox_3);
        dial_volume_3->setObjectName(QString::fromUtf8("dial_volume_3"));
        dial_volume_3->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_3->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_3->setMaximum(1000);
        dial_volume_3->setValue(1000);
        groupBox_master_controls = new QGroupBox(centralwidget);
        groupBox_master_controls->setObjectName(QString::fromUtf8("groupBox_master_controls"));
        groupBox_master_controls->setGeometry(QRect(40, 20, 771, 101));
        groupBox_master_controls->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_master_pitch = new QDial(groupBox_master_controls);
        dial_master_pitch->setObjectName(QString::fromUtf8("dial_master_pitch"));
        dial_master_pitch->setGeometry(QRect(20, 20, 61, 61));
        dial_master_pitch->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_master_pitch->setMinimum(-500);
        dial_master_pitch->setMaximum(500);
        dial_master_fm_amount = new QDial(groupBox_master_controls);
        dial_master_fm_amount->setObjectName(QString::fromUtf8("dial_master_fm_amount"));
        dial_master_fm_amount->setGeometry(QRect(90, 20, 61, 61));
        dial_master_fm_amount->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_master_fm_amount->setMinimum(-500);
        dial_master_fm_amount->setMaximum(500);
        dial_master_volume = new QDial(groupBox_master_controls);
        dial_master_volume->setObjectName(QString::fromUtf8("dial_master_volume"));
        dial_master_volume->setGeometry(QRect(160, 20, 61, 61));
        dial_master_volume->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_master_volume->setMaximum(1000);
        dial_master_volume->setValue(1000);
        dial_master_volume_2 = new QDial(groupBox_master_controls);
        dial_master_volume_2->setObjectName(QString::fromUtf8("dial_master_volume_2"));
        dial_master_volume_2->setGeometry(QRect(680, 20, 61, 61));
        dial_master_volume_2->setStyleSheet(QString::fromUtf8("background-color: mediumaquamarine"));
        dial_master_volume_2->setMinimum(60);
        dial_master_volume_2->setMaximum(180);
        dial_master_volume_2->setValue(120);
        MainWindow->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        groupBox_1->setTitle(QString());
        groupBox_labels->setTitle(QString());
        label_pitch->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">PITCH</span></p></body></html>", nullptr));
        label_ramp->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">RAMP</span></p></body></html>", nullptr));
        label_ramp_decay->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">DECAY</span></p></body></html>", nullptr));
        label_fm_amount->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">FM</span></p></body></html>", nullptr));
        label_fm_frequency->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">FREQ</span></p></body></html>", nullptr));
        label_fm_decay->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">DECAY</span></p></body></html>", nullptr));
        label_fm_feedback->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">FB</span></p></body></html>", nullptr));
        label_aeg->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">AEG</span></p></body></html>", nullptr));
        label_volume->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">VOLUME</span></p><p align=\"center\"><br/></p></body></html>", nullptr));
        groupBox_4->setTitle(QString());
        groupBox_5->setTitle(QString());
        groupBox_6->setTitle(QString());
        groupBox_7->setTitle(QString());
        groupBox_8->setTitle(QString());
        groupBox_9->setTitle(QString());
        groupBox_10->setTitle(QString());
        groupBox_11->setTitle(QString());
        groupBox_12->setTitle(QString());
        groupBox_13->setTitle(QString());
        groupBox_14->setTitle(QString());
        groupBox_15->setTitle(QString());
        groupBox_16->setTitle(QString());
        groupBox_2->setTitle(QString());
        groupBox_3->setTitle(QString());
        groupBox_master_controls->setTitle(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
