/********************************************************************************
** Form generated from reading UI file 'mega_fm_8step.ui'
**
** Created by: Qt User Interface Compiler version 5.12.8
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDial>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QGroupBox *groupBox_1;
    QDial *dial_pitch_1;
    QDial *dial_ramp_amount_1;
    QDial *dial_ramp_decay_1;
    QDial *dial_fm_amount_1;
    QDial *dial_fm_freq_1;
    QDial *dial_fm_decay_1;
    QDial *dial_fm_feedback_1;
    QDial *dial_amp_decay_1;
    QDial *dial_volume_1;
    QPushButton *btn_step_1;
    QPushButton *btn_step_9;
    QGroupBox *groupBox_labels;
    QLabel *label_pitch;
    QLabel *label_ramp;
    QLabel *label_ramp_decay;
    QLabel *label_fm_amount;
    QLabel *label_fm_frequency;
    QLabel *label_fm_decay;
    QLabel *label_fm_feedback;
    QLabel *label_aeg;
    QLabel *label_volume;
    QLabel *label_volume_2;
    QGroupBox *groupBox_4;
    QDial *dial_pitch_4;
    QDial *dial_ramp_amount_4;
    QDial *dial_ramp_decay_4;
    QDial *dial_fm_amount_4;
    QDial *dial_fm_freq_4;
    QDial *dial_fm_decay_4;
    QDial *dial_fm_feedback_4;
    QDial *dial_amp_decay_4;
    QDial *dial_volume_4;
    QPushButton *btn_step_4;
    QPushButton *btn_step_12;
    QGroupBox *groupBox_5;
    QDial *dial_pitch_5;
    QDial *dial_ramp_amount_5;
    QDial *dial_ramp_decay_5;
    QDial *dial_fm_amount_5;
    QDial *dial_5_fm_freq_5;
    QDial *dial_fm_decay_5;
    QDial *dial_fm_feedback_5;
    QDial *dial_amp_decay_5;
    QDial *dial_volume_5;
    QPushButton *btn_step_5;
    QPushButton *btn_step_13;
    QGroupBox *groupBox_6;
    QDial *dial_pitch_6;
    QDial *dial_ramp_amount_6;
    QDial *dial_ramp_decay_6;
    QDial *dial_fm_amount_6;
    QDial *dial_5_fm_freq_6;
    QDial *dial_fm_decay_6;
    QDial *dial_fm_feedback_6;
    QDial *dial_amp_decay_6;
    QDial *dial_volume_6;
    QPushButton *btn_step_6;
    QPushButton *btn_step_14;
    QGroupBox *groupBox_7;
    QDial *dial_pitch_7;
    QDial *dial_ramp_amount_7;
    QDial *dial_ramp_decay_7;
    QDial *dial_fm_amount_7;
    QDial *dial_5_fm_freq_7;
    QDial *dial_fm_decay_7;
    QDial *dial_fm_feedback_7;
    QDial *dial_amp_decay_7;
    QDial *dial_volume_7;
    QPushButton *btn_step_7;
    QPushButton *btn_step_15;
    QGroupBox *groupBox_8;
    QDial *dial_pitch_8;
    QDial *dial_ramp_amount_8;
    QDial *dial_ramp_decay_8;
    QDial *dial_fm_amount_8;
    QDial *dial_5_fm_freq_8;
    QDial *dial_fm_decay_8;
    QDial *dial_fm_feedback_8;
    QDial *dial_amp_decay_8;
    QDial *dial_volume_8;
    QPushButton *btn_step_8;
    QPushButton *btn_step_16;
    QGroupBox *groupBox_2;
    QDial *dial_pitch_2;
    QDial *dial_ramp_amount_2;
    QDial *dial_ramp_decay_2;
    QDial *dial_fm_amount_2;
    QDial *dial_fm_freq_2;
    QDial *dial_fm_decay_2;
    QDial *dial_fm_feedback_2;
    QDial *dial_amp_decay_2;
    QDial *dial_volume_2;
    QPushButton *btn_step_2;
    QPushButton *btn_step_10;
    QGroupBox *groupBox_3;
    QDial *dial_pitch_3;
    QDial *dial_ramp_amount_3;
    QDial *dial_ramp_decay_3;
    QDial *dial_fm_amount_3;
    QDial *dial_fm_freq_3;
    QDial *dial_fm_decay_3;
    QDial *dial_fm_feedback_3;
    QDial *dial_amp_decay_3;
    QDial *dial_volume_3;
    QPushButton *btn_step_3;
    QPushButton *btn_step_11;
    QGroupBox *groupBox_master_controls;
    QDial *dial_master_pitch;
    QDial *dial_master_fm_amount;
    QDial *dial_master_volume;
    QDial *dial_tempo;
    QLabel *label_master_pitch;
    QLabel *label_master_fm_amount;
    QLabel *label_master_volume;
    QLabel *label_master_volume_2;
    QGroupBox *groupBox;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(472, 635);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        groupBox_1 = new QGroupBox(centralwidget);
        groupBox_1->setObjectName(QString::fromUtf8("groupBox_1"));
        groupBox_1->setGeometry(QRect(120, 133, 41, 471));
        groupBox_1->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_1 = new QDial(groupBox_1);
        dial_pitch_1->setObjectName(QString::fromUtf8("dial_pitch_1"));
        dial_pitch_1->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_1->setStyleSheet(QString::fromUtf8("background-color: lightblue; "));
        dial_pitch_1->setMinimum(-500);
        dial_pitch_1->setMaximum(500);
        dial_ramp_amount_1 = new QDial(groupBox_1);
        dial_ramp_amount_1->setObjectName(QString::fromUtf8("dial_ramp_amount_1"));
        dial_ramp_amount_1->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_1->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_amount_1->setMaximum(1000);
        dial_ramp_decay_1 = new QDial(groupBox_1);
        dial_ramp_decay_1->setObjectName(QString::fromUtf8("dial_ramp_decay_1"));
        dial_ramp_decay_1->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_1->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_decay_1->setMaximum(1000);
        dial_fm_amount_1 = new QDial(groupBox_1);
        dial_fm_amount_1->setObjectName(QString::fromUtf8("dial_fm_amount_1"));
        dial_fm_amount_1->setGeometry(QRect(0, 153, 41, 41));
        dial_fm_amount_1->setAutoFillBackground(false);
        dial_fm_amount_1->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_amount_1->setMaximum(1000);
        dial_fm_freq_1 = new QDial(groupBox_1);
        dial_fm_freq_1->setObjectName(QString::fromUtf8("dial_fm_freq_1"));
        dial_fm_freq_1->setGeometry(QRect(0, 193, 41, 41));
        dial_fm_freq_1->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_freq_1->setMaximum(1000);
        dial_fm_decay_1 = new QDial(groupBox_1);
        dial_fm_decay_1->setObjectName(QString::fromUtf8("dial_fm_decay_1"));
        dial_fm_decay_1->setGeometry(QRect(0, 233, 41, 41));
        dial_fm_decay_1->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_decay_1->setMaximum(1000);
        dial_fm_feedback_1 = new QDial(groupBox_1);
        dial_fm_feedback_1->setObjectName(QString::fromUtf8("dial_fm_feedback_1"));
        dial_fm_feedback_1->setGeometry(QRect(0, 273, 41, 41));
        dial_fm_feedback_1->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_feedback_1->setMaximum(1000);
        dial_amp_decay_1 = new QDial(groupBox_1);
        dial_amp_decay_1->setObjectName(QString::fromUtf8("dial_amp_decay_1"));
        dial_amp_decay_1->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_1->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_1->setMaximum(1000);
        dial_amp_decay_1->setValue(500);
        dial_volume_1 = new QDial(groupBox_1);
        dial_volume_1->setObjectName(QString::fromUtf8("dial_volume_1"));
        dial_volume_1->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_1->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_1->setMaximum(1000);
        dial_volume_1->setValue(1000);
        btn_step_1 = new QPushButton(groupBox_1);
        btn_step_1->setObjectName(QString::fromUtf8("btn_step_1"));
        btn_step_1->setGeometry(QRect(12, 420, 16, 16));
        btn_step_1->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        btn_step_9 = new QPushButton(groupBox_1);
        btn_step_9->setObjectName(QString::fromUtf8("btn_step_9"));
        btn_step_9->setGeometry(QRect(12, 442, 16, 16));
        btn_step_9->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        groupBox_labels = new QGroupBox(centralwidget);
        groupBox_labels->setObjectName(QString::fromUtf8("groupBox_labels"));
        groupBox_labels->setGeometry(QRect(20, 133, 91, 471));
        groupBox_labels->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        label_pitch = new QLabel(groupBox_labels);
        label_pitch->setObjectName(QString::fromUtf8("label_pitch"));
        label_pitch->setGeometry(QRect(10, 30, 67, 21));
        label_pitch->setStyleSheet(QString::fromUtf8("border: 1px solid black; background-color:lightblue;"));
        label_ramp = new QLabel(groupBox_labels);
        label_ramp->setObjectName(QString::fromUtf8("label_ramp"));
        label_ramp->setGeometry(QRect(10, 70, 67, 21));
        label_ramp->setStyleSheet(QString::fromUtf8("border: 1px solid black; background-color:lightblue;"));
        label_ramp_decay = new QLabel(groupBox_labels);
        label_ramp_decay->setObjectName(QString::fromUtf8("label_ramp_decay"));
        label_ramp_decay->setGeometry(QRect(10, 110, 67, 21));
        label_ramp_decay->setStyleSheet(QString::fromUtf8("border: 1px solid black; background-color:lightblue;"));
        label_fm_amount = new QLabel(groupBox_labels);
        label_fm_amount->setObjectName(QString::fromUtf8("label_fm_amount"));
        label_fm_amount->setGeometry(QRect(10, 163, 67, 21));
        label_fm_amount->setStyleSheet(QString::fromUtf8("border: 1px solid black; background-color:pink;"));
        label_fm_frequency = new QLabel(groupBox_labels);
        label_fm_frequency->setObjectName(QString::fromUtf8("label_fm_frequency"));
        label_fm_frequency->setGeometry(QRect(10, 203, 67, 21));
        label_fm_frequency->setStyleSheet(QString::fromUtf8("border: 1px solid black; background-color:pink;"));
        label_fm_decay = new QLabel(groupBox_labels);
        label_fm_decay->setObjectName(QString::fromUtf8("label_fm_decay"));
        label_fm_decay->setGeometry(QRect(10, 243, 67, 21));
        label_fm_decay->setStyleSheet(QString::fromUtf8("border: 1px solid black; background-color:pink;"));
        label_fm_feedback = new QLabel(groupBox_labels);
        label_fm_feedback->setObjectName(QString::fromUtf8("label_fm_feedback"));
        label_fm_feedback->setGeometry(QRect(10, 283, 67, 21));
        label_fm_feedback->setStyleSheet(QString::fromUtf8("border: 1px solid black; background-color:pink;"));
        label_aeg = new QLabel(groupBox_labels);
        label_aeg->setObjectName(QString::fromUtf8("label_aeg"));
        label_aeg->setGeometry(QRect(10, 340, 67, 21));
        label_aeg->setStyleSheet(QString::fromUtf8("border: 1px solid black; background-color:lightgray;"));
        label_volume = new QLabel(groupBox_labels);
        label_volume->setObjectName(QString::fromUtf8("label_volume"));
        label_volume->setGeometry(QRect(10, 380, 67, 21));
        label_volume->setStyleSheet(QString::fromUtf8("border: 1px solid black; background-color:lightgray;"));
        label_volume_2 = new QLabel(groupBox_labels);
        label_volume_2->setObjectName(QString::fromUtf8("label_volume_2"));
        label_volume_2->setGeometry(QRect(10, 423, 67, 21));
        label_volume_2->setStyleSheet(QString::fromUtf8("border: 1px solid black; background-color:mediumaquamarine;"));
        groupBox_4 = new QGroupBox(centralwidget);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(240, 133, 41, 471));
        groupBox_4->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_4 = new QDial(groupBox_4);
        dial_pitch_4->setObjectName(QString::fromUtf8("dial_pitch_4"));
        dial_pitch_4->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_4->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_pitch_4->setMinimum(-500);
        dial_pitch_4->setMaximum(500);
        dial_ramp_amount_4 = new QDial(groupBox_4);
        dial_ramp_amount_4->setObjectName(QString::fromUtf8("dial_ramp_amount_4"));
        dial_ramp_amount_4->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_4->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_amount_4->setMaximum(1000);
        dial_ramp_decay_4 = new QDial(groupBox_4);
        dial_ramp_decay_4->setObjectName(QString::fromUtf8("dial_ramp_decay_4"));
        dial_ramp_decay_4->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_4->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_decay_4->setMaximum(1000);
        dial_fm_amount_4 = new QDial(groupBox_4);
        dial_fm_amount_4->setObjectName(QString::fromUtf8("dial_fm_amount_4"));
        dial_fm_amount_4->setGeometry(QRect(0, 153, 41, 41));
        dial_fm_amount_4->setAutoFillBackground(false);
        dial_fm_amount_4->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_amount_4->setMaximum(1000);
        dial_fm_freq_4 = new QDial(groupBox_4);
        dial_fm_freq_4->setObjectName(QString::fromUtf8("dial_fm_freq_4"));
        dial_fm_freq_4->setGeometry(QRect(0, 193, 41, 41));
        dial_fm_freq_4->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_freq_4->setMaximum(1000);
        dial_fm_decay_4 = new QDial(groupBox_4);
        dial_fm_decay_4->setObjectName(QString::fromUtf8("dial_fm_decay_4"));
        dial_fm_decay_4->setGeometry(QRect(0, 233, 41, 41));
        dial_fm_decay_4->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_decay_4->setMaximum(1000);
        dial_fm_feedback_4 = new QDial(groupBox_4);
        dial_fm_feedback_4->setObjectName(QString::fromUtf8("dial_fm_feedback_4"));
        dial_fm_feedback_4->setGeometry(QRect(0, 273, 41, 41));
        dial_fm_feedback_4->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_feedback_4->setMaximum(1000);
        dial_amp_decay_4 = new QDial(groupBox_4);
        dial_amp_decay_4->setObjectName(QString::fromUtf8("dial_amp_decay_4"));
        dial_amp_decay_4->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_4->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_4->setMaximum(1000);
        dial_amp_decay_4->setValue(500);
        dial_volume_4 = new QDial(groupBox_4);
        dial_volume_4->setObjectName(QString::fromUtf8("dial_volume_4"));
        dial_volume_4->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_4->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_4->setMaximum(1000);
        dial_volume_4->setValue(1000);
        btn_step_4 = new QPushButton(groupBox_4);
        btn_step_4->setObjectName(QString::fromUtf8("btn_step_4"));
        btn_step_4->setGeometry(QRect(12, 420, 16, 16));
        btn_step_4->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        btn_step_12 = new QPushButton(groupBox_4);
        btn_step_12->setObjectName(QString::fromUtf8("btn_step_12"));
        btn_step_12->setGeometry(QRect(12, 442, 16, 16));
        btn_step_12->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        groupBox_5 = new QGroupBox(centralwidget);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(290, 133, 41, 471));
        groupBox_5->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_5 = new QDial(groupBox_5);
        dial_pitch_5->setObjectName(QString::fromUtf8("dial_pitch_5"));
        dial_pitch_5->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_5->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_pitch_5->setMinimum(-500);
        dial_pitch_5->setMaximum(500);
        dial_ramp_amount_5 = new QDial(groupBox_5);
        dial_ramp_amount_5->setObjectName(QString::fromUtf8("dial_ramp_amount_5"));
        dial_ramp_amount_5->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_5->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_amount_5->setMaximum(1000);
        dial_ramp_decay_5 = new QDial(groupBox_5);
        dial_ramp_decay_5->setObjectName(QString::fromUtf8("dial_ramp_decay_5"));
        dial_ramp_decay_5->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_5->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_decay_5->setMaximum(1000);
        dial_fm_amount_5 = new QDial(groupBox_5);
        dial_fm_amount_5->setObjectName(QString::fromUtf8("dial_fm_amount_5"));
        dial_fm_amount_5->setGeometry(QRect(0, 153, 41, 41));
        dial_fm_amount_5->setAutoFillBackground(false);
        dial_fm_amount_5->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_amount_5->setMaximum(1000);
        dial_5_fm_freq_5 = new QDial(groupBox_5);
        dial_5_fm_freq_5->setObjectName(QString::fromUtf8("dial_5_fm_freq_5"));
        dial_5_fm_freq_5->setGeometry(QRect(0, 193, 41, 41));
        dial_5_fm_freq_5->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_5_fm_freq_5->setMaximum(1000);
        dial_fm_decay_5 = new QDial(groupBox_5);
        dial_fm_decay_5->setObjectName(QString::fromUtf8("dial_fm_decay_5"));
        dial_fm_decay_5->setGeometry(QRect(0, 233, 41, 41));
        dial_fm_decay_5->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_decay_5->setMaximum(1000);
        dial_fm_feedback_5 = new QDial(groupBox_5);
        dial_fm_feedback_5->setObjectName(QString::fromUtf8("dial_fm_feedback_5"));
        dial_fm_feedback_5->setGeometry(QRect(0, 273, 41, 41));
        dial_fm_feedback_5->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_feedback_5->setMaximum(1000);
        dial_amp_decay_5 = new QDial(groupBox_5);
        dial_amp_decay_5->setObjectName(QString::fromUtf8("dial_amp_decay_5"));
        dial_amp_decay_5->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_5->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_5->setMaximum(1000);
        dial_amp_decay_5->setValue(500);
        dial_volume_5 = new QDial(groupBox_5);
        dial_volume_5->setObjectName(QString::fromUtf8("dial_volume_5"));
        dial_volume_5->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_5->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_5->setMaximum(1000);
        dial_volume_5->setValue(1000);
        btn_step_5 = new QPushButton(groupBox_5);
        btn_step_5->setObjectName(QString::fromUtf8("btn_step_5"));
        btn_step_5->setGeometry(QRect(12, 420, 16, 16));
        btn_step_5->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        btn_step_13 = new QPushButton(groupBox_5);
        btn_step_13->setObjectName(QString::fromUtf8("btn_step_13"));
        btn_step_13->setGeometry(QRect(12, 442, 16, 16));
        btn_step_13->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        groupBox_6 = new QGroupBox(centralwidget);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(330, 133, 41, 471));
        groupBox_6->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_6 = new QDial(groupBox_6);
        dial_pitch_6->setObjectName(QString::fromUtf8("dial_pitch_6"));
        dial_pitch_6->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_6->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_pitch_6->setMinimum(-500);
        dial_pitch_6->setMaximum(500);
        dial_ramp_amount_6 = new QDial(groupBox_6);
        dial_ramp_amount_6->setObjectName(QString::fromUtf8("dial_ramp_amount_6"));
        dial_ramp_amount_6->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_6->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_amount_6->setMaximum(1000);
        dial_ramp_decay_6 = new QDial(groupBox_6);
        dial_ramp_decay_6->setObjectName(QString::fromUtf8("dial_ramp_decay_6"));
        dial_ramp_decay_6->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_6->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_decay_6->setMaximum(1000);
        dial_fm_amount_6 = new QDial(groupBox_6);
        dial_fm_amount_6->setObjectName(QString::fromUtf8("dial_fm_amount_6"));
        dial_fm_amount_6->setGeometry(QRect(0, 153, 41, 41));
        dial_fm_amount_6->setAutoFillBackground(false);
        dial_fm_amount_6->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_amount_6->setMaximum(1000);
        dial_5_fm_freq_6 = new QDial(groupBox_6);
        dial_5_fm_freq_6->setObjectName(QString::fromUtf8("dial_5_fm_freq_6"));
        dial_5_fm_freq_6->setGeometry(QRect(0, 193, 41, 41));
        dial_5_fm_freq_6->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_5_fm_freq_6->setMaximum(1000);
        dial_fm_decay_6 = new QDial(groupBox_6);
        dial_fm_decay_6->setObjectName(QString::fromUtf8("dial_fm_decay_6"));
        dial_fm_decay_6->setGeometry(QRect(0, 233, 41, 41));
        dial_fm_decay_6->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_decay_6->setMaximum(1000);
        dial_fm_feedback_6 = new QDial(groupBox_6);
        dial_fm_feedback_6->setObjectName(QString::fromUtf8("dial_fm_feedback_6"));
        dial_fm_feedback_6->setGeometry(QRect(0, 273, 41, 41));
        dial_fm_feedback_6->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_feedback_6->setMaximum(1000);
        dial_amp_decay_6 = new QDial(groupBox_6);
        dial_amp_decay_6->setObjectName(QString::fromUtf8("dial_amp_decay_6"));
        dial_amp_decay_6->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_6->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_6->setMaximum(1000);
        dial_amp_decay_6->setValue(500);
        dial_volume_6 = new QDial(groupBox_6);
        dial_volume_6->setObjectName(QString::fromUtf8("dial_volume_6"));
        dial_volume_6->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_6->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_6->setMaximum(1000);
        dial_volume_6->setValue(1000);
        btn_step_6 = new QPushButton(groupBox_6);
        btn_step_6->setObjectName(QString::fromUtf8("btn_step_6"));
        btn_step_6->setGeometry(QRect(12, 420, 16, 16));
        btn_step_6->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        btn_step_14 = new QPushButton(groupBox_6);
        btn_step_14->setObjectName(QString::fromUtf8("btn_step_14"));
        btn_step_14->setGeometry(QRect(12, 442, 16, 16));
        btn_step_14->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        groupBox_7 = new QGroupBox(centralwidget);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(370, 133, 41, 471));
        groupBox_7->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_7 = new QDial(groupBox_7);
        dial_pitch_7->setObjectName(QString::fromUtf8("dial_pitch_7"));
        dial_pitch_7->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_7->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_pitch_7->setMinimum(-500);
        dial_pitch_7->setMaximum(500);
        dial_ramp_amount_7 = new QDial(groupBox_7);
        dial_ramp_amount_7->setObjectName(QString::fromUtf8("dial_ramp_amount_7"));
        dial_ramp_amount_7->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_7->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_amount_7->setMaximum(1000);
        dial_ramp_decay_7 = new QDial(groupBox_7);
        dial_ramp_decay_7->setObjectName(QString::fromUtf8("dial_ramp_decay_7"));
        dial_ramp_decay_7->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_7->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_decay_7->setMaximum(1000);
        dial_fm_amount_7 = new QDial(groupBox_7);
        dial_fm_amount_7->setObjectName(QString::fromUtf8("dial_fm_amount_7"));
        dial_fm_amount_7->setGeometry(QRect(0, 153, 41, 41));
        dial_fm_amount_7->setAutoFillBackground(false);
        dial_fm_amount_7->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_amount_7->setMaximum(1000);
        dial_5_fm_freq_7 = new QDial(groupBox_7);
        dial_5_fm_freq_7->setObjectName(QString::fromUtf8("dial_5_fm_freq_7"));
        dial_5_fm_freq_7->setGeometry(QRect(0, 193, 41, 41));
        dial_5_fm_freq_7->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_5_fm_freq_7->setMaximum(1000);
        dial_fm_decay_7 = new QDial(groupBox_7);
        dial_fm_decay_7->setObjectName(QString::fromUtf8("dial_fm_decay_7"));
        dial_fm_decay_7->setGeometry(QRect(0, 233, 41, 41));
        dial_fm_decay_7->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_decay_7->setMaximum(1000);
        dial_fm_feedback_7 = new QDial(groupBox_7);
        dial_fm_feedback_7->setObjectName(QString::fromUtf8("dial_fm_feedback_7"));
        dial_fm_feedback_7->setGeometry(QRect(0, 273, 41, 41));
        dial_fm_feedback_7->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_feedback_7->setMaximum(1000);
        dial_amp_decay_7 = new QDial(groupBox_7);
        dial_amp_decay_7->setObjectName(QString::fromUtf8("dial_amp_decay_7"));
        dial_amp_decay_7->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_7->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_7->setMaximum(1000);
        dial_amp_decay_7->setValue(500);
        dial_volume_7 = new QDial(groupBox_7);
        dial_volume_7->setObjectName(QString::fromUtf8("dial_volume_7"));
        dial_volume_7->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_7->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_7->setMaximum(1000);
        dial_volume_7->setValue(1000);
        btn_step_7 = new QPushButton(groupBox_7);
        btn_step_7->setObjectName(QString::fromUtf8("btn_step_7"));
        btn_step_7->setGeometry(QRect(12, 420, 16, 16));
        btn_step_7->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        btn_step_15 = new QPushButton(groupBox_7);
        btn_step_15->setObjectName(QString::fromUtf8("btn_step_15"));
        btn_step_15->setGeometry(QRect(12, 442, 16, 16));
        btn_step_15->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        groupBox_8 = new QGroupBox(centralwidget);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(410, 133, 41, 471));
        groupBox_8->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_8 = new QDial(groupBox_8);
        dial_pitch_8->setObjectName(QString::fromUtf8("dial_pitch_8"));
        dial_pitch_8->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_8->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_pitch_8->setMinimum(-500);
        dial_pitch_8->setMaximum(500);
        dial_ramp_amount_8 = new QDial(groupBox_8);
        dial_ramp_amount_8->setObjectName(QString::fromUtf8("dial_ramp_amount_8"));
        dial_ramp_amount_8->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_8->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_amount_8->setMaximum(1000);
        dial_ramp_decay_8 = new QDial(groupBox_8);
        dial_ramp_decay_8->setObjectName(QString::fromUtf8("dial_ramp_decay_8"));
        dial_ramp_decay_8->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_8->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_decay_8->setMaximum(1000);
        dial_fm_amount_8 = new QDial(groupBox_8);
        dial_fm_amount_8->setObjectName(QString::fromUtf8("dial_fm_amount_8"));
        dial_fm_amount_8->setGeometry(QRect(0, 153, 41, 41));
        dial_fm_amount_8->setAutoFillBackground(false);
        dial_fm_amount_8->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_amount_8->setMaximum(1000);
        dial_5_fm_freq_8 = new QDial(groupBox_8);
        dial_5_fm_freq_8->setObjectName(QString::fromUtf8("dial_5_fm_freq_8"));
        dial_5_fm_freq_8->setGeometry(QRect(0, 193, 41, 41));
        dial_5_fm_freq_8->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_5_fm_freq_8->setMaximum(1000);
        dial_fm_decay_8 = new QDial(groupBox_8);
        dial_fm_decay_8->setObjectName(QString::fromUtf8("dial_fm_decay_8"));
        dial_fm_decay_8->setGeometry(QRect(0, 233, 41, 41));
        dial_fm_decay_8->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_decay_8->setMaximum(1000);
        dial_fm_feedback_8 = new QDial(groupBox_8);
        dial_fm_feedback_8->setObjectName(QString::fromUtf8("dial_fm_feedback_8"));
        dial_fm_feedback_8->setGeometry(QRect(0, 273, 41, 41));
        dial_fm_feedback_8->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_feedback_8->setMaximum(1000);
        dial_amp_decay_8 = new QDial(groupBox_8);
        dial_amp_decay_8->setObjectName(QString::fromUtf8("dial_amp_decay_8"));
        dial_amp_decay_8->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_8->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_8->setMaximum(1000);
        dial_amp_decay_8->setValue(500);
        dial_volume_8 = new QDial(groupBox_8);
        dial_volume_8->setObjectName(QString::fromUtf8("dial_volume_8"));
        dial_volume_8->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_8->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_8->setMaximum(1000);
        dial_volume_8->setValue(1000);
        btn_step_8 = new QPushButton(groupBox_8);
        btn_step_8->setObjectName(QString::fromUtf8("btn_step_8"));
        btn_step_8->setGeometry(QRect(12, 420, 16, 16));
        btn_step_8->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        btn_step_16 = new QPushButton(groupBox_8);
        btn_step_16->setObjectName(QString::fromUtf8("btn_step_16"));
        btn_step_16->setGeometry(QRect(12, 442, 16, 16));
        btn_step_16->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        groupBox_2 = new QGroupBox(centralwidget);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(160, 133, 41, 471));
        groupBox_2->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_2 = new QDial(groupBox_2);
        dial_pitch_2->setObjectName(QString::fromUtf8("dial_pitch_2"));
        dial_pitch_2->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_2->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_pitch_2->setMinimum(-500);
        dial_pitch_2->setMaximum(500);
        dial_ramp_amount_2 = new QDial(groupBox_2);
        dial_ramp_amount_2->setObjectName(QString::fromUtf8("dial_ramp_amount_2"));
        dial_ramp_amount_2->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_2->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_amount_2->setMaximum(1000);
        dial_ramp_decay_2 = new QDial(groupBox_2);
        dial_ramp_decay_2->setObjectName(QString::fromUtf8("dial_ramp_decay_2"));
        dial_ramp_decay_2->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_2->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_decay_2->setMaximum(1000);
        dial_fm_amount_2 = new QDial(groupBox_2);
        dial_fm_amount_2->setObjectName(QString::fromUtf8("dial_fm_amount_2"));
        dial_fm_amount_2->setGeometry(QRect(0, 153, 41, 41));
        dial_fm_amount_2->setAutoFillBackground(false);
        dial_fm_amount_2->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_amount_2->setMaximum(1000);
        dial_fm_freq_2 = new QDial(groupBox_2);
        dial_fm_freq_2->setObjectName(QString::fromUtf8("dial_fm_freq_2"));
        dial_fm_freq_2->setGeometry(QRect(0, 193, 41, 41));
        dial_fm_freq_2->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_freq_2->setMaximum(1000);
        dial_fm_decay_2 = new QDial(groupBox_2);
        dial_fm_decay_2->setObjectName(QString::fromUtf8("dial_fm_decay_2"));
        dial_fm_decay_2->setGeometry(QRect(0, 233, 41, 41));
        dial_fm_decay_2->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_decay_2->setMaximum(1000);
        dial_fm_feedback_2 = new QDial(groupBox_2);
        dial_fm_feedback_2->setObjectName(QString::fromUtf8("dial_fm_feedback_2"));
        dial_fm_feedback_2->setGeometry(QRect(0, 273, 41, 41));
        dial_fm_feedback_2->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_feedback_2->setMaximum(1000);
        dial_amp_decay_2 = new QDial(groupBox_2);
        dial_amp_decay_2->setObjectName(QString::fromUtf8("dial_amp_decay_2"));
        dial_amp_decay_2->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_2->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_2->setMaximum(1000);
        dial_amp_decay_2->setValue(500);
        dial_volume_2 = new QDial(groupBox_2);
        dial_volume_2->setObjectName(QString::fromUtf8("dial_volume_2"));
        dial_volume_2->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_2->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_2->setMaximum(1000);
        dial_volume_2->setValue(1000);
        btn_step_2 = new QPushButton(groupBox_2);
        btn_step_2->setObjectName(QString::fromUtf8("btn_step_2"));
        btn_step_2->setGeometry(QRect(12, 420, 16, 16));
        btn_step_2->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        btn_step_10 = new QPushButton(groupBox_2);
        btn_step_10->setObjectName(QString::fromUtf8("btn_step_10"));
        btn_step_10->setGeometry(QRect(12, 442, 16, 16));
        btn_step_10->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        groupBox_3 = new QGroupBox(centralwidget);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(200, 133, 41, 471));
        groupBox_3->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_pitch_3 = new QDial(groupBox_3);
        dial_pitch_3->setObjectName(QString::fromUtf8("dial_pitch_3"));
        dial_pitch_3->setGeometry(QRect(0, 20, 41, 41));
        dial_pitch_3->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_pitch_3->setMinimum(-500);
        dial_pitch_3->setMaximum(500);
        dial_ramp_amount_3 = new QDial(groupBox_3);
        dial_ramp_amount_3->setObjectName(QString::fromUtf8("dial_ramp_amount_3"));
        dial_ramp_amount_3->setGeometry(QRect(0, 60, 41, 41));
        dial_ramp_amount_3->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_amount_3->setMaximum(1000);
        dial_ramp_decay_3 = new QDial(groupBox_3);
        dial_ramp_decay_3->setObjectName(QString::fromUtf8("dial_ramp_decay_3"));
        dial_ramp_decay_3->setGeometry(QRect(0, 100, 41, 41));
        dial_ramp_decay_3->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_ramp_decay_3->setMaximum(1000);
        dial_fm_amount_3 = new QDial(groupBox_3);
        dial_fm_amount_3->setObjectName(QString::fromUtf8("dial_fm_amount_3"));
        dial_fm_amount_3->setGeometry(QRect(0, 153, 41, 41));
        dial_fm_amount_3->setAutoFillBackground(false);
        dial_fm_amount_3->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_amount_3->setMaximum(1000);
        dial_fm_freq_3 = new QDial(groupBox_3);
        dial_fm_freq_3->setObjectName(QString::fromUtf8("dial_fm_freq_3"));
        dial_fm_freq_3->setGeometry(QRect(0, 193, 41, 41));
        dial_fm_freq_3->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_freq_3->setMaximum(1000);
        dial_fm_decay_3 = new QDial(groupBox_3);
        dial_fm_decay_3->setObjectName(QString::fromUtf8("dial_fm_decay_3"));
        dial_fm_decay_3->setGeometry(QRect(0, 233, 41, 41));
        dial_fm_decay_3->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_decay_3->setMaximum(1000);
        dial_fm_feedback_3 = new QDial(groupBox_3);
        dial_fm_feedback_3->setObjectName(QString::fromUtf8("dial_fm_feedback_3"));
        dial_fm_feedback_3->setGeometry(QRect(0, 273, 41, 41));
        dial_fm_feedback_3->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_fm_feedback_3->setMaximum(1000);
        dial_amp_decay_3 = new QDial(groupBox_3);
        dial_amp_decay_3->setObjectName(QString::fromUtf8("dial_amp_decay_3"));
        dial_amp_decay_3->setGeometry(QRect(0, 330, 41, 41));
        dial_amp_decay_3->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_amp_decay_3->setMaximum(1000);
        dial_amp_decay_3->setValue(500);
        dial_volume_3 = new QDial(groupBox_3);
        dial_volume_3->setObjectName(QString::fromUtf8("dial_volume_3"));
        dial_volume_3->setGeometry(QRect(0, 370, 41, 41));
        dial_volume_3->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_volume_3->setMaximum(1000);
        dial_volume_3->setValue(1000);
        btn_step_3 = new QPushButton(groupBox_3);
        btn_step_3->setObjectName(QString::fromUtf8("btn_step_3"));
        btn_step_3->setGeometry(QRect(12, 420, 16, 16));
        btn_step_3->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        btn_step_11 = new QPushButton(groupBox_3);
        btn_step_11->setObjectName(QString::fromUtf8("btn_step_11"));
        btn_step_11->setGeometry(QRect(12, 442, 16, 16));
        btn_step_11->setStyleSheet(QString::fromUtf8("border-radius:3; border: 1px solid black;"));
        groupBox_master_controls = new QGroupBox(centralwidget);
        groupBox_master_controls->setObjectName(QString::fromUtf8("groupBox_master_controls"));
        groupBox_master_controls->setGeometry(QRect(20, 23, 431, 101));
        groupBox_master_controls->setStyleSheet(QString::fromUtf8("border: 2px solid black; border-radius: 10; background-color: gray"));
        dial_master_pitch = new QDial(groupBox_master_controls);
        dial_master_pitch->setObjectName(QString::fromUtf8("dial_master_pitch"));
        dial_master_pitch->setGeometry(QRect(20, 10, 61, 61));
        dial_master_pitch->setStyleSheet(QString::fromUtf8("background-color: lightblue"));
        dial_master_pitch->setMinimum(-500);
        dial_master_pitch->setMaximum(500);
        dial_master_fm_amount = new QDial(groupBox_master_controls);
        dial_master_fm_amount->setObjectName(QString::fromUtf8("dial_master_fm_amount"));
        dial_master_fm_amount->setGeometry(QRect(130, 10, 61, 61));
        dial_master_fm_amount->setToolTipDuration(-1);
        dial_master_fm_amount->setStyleSheet(QString::fromUtf8("background-color: pink"));
        dial_master_fm_amount->setMinimum(500);
        dial_master_fm_amount->setMaximum(2000);
        dial_master_fm_amount->setValue(1000);
        dial_master_fm_amount->setInvertedAppearance(false);
        dial_master_fm_amount->setWrapping(false);
        dial_master_fm_amount->setNotchTarget(3.700000000000000);
        dial_master_fm_amount->setNotchesVisible(true);
        dial_master_volume = new QDial(groupBox_master_controls);
        dial_master_volume->setObjectName(QString::fromUtf8("dial_master_volume"));
        dial_master_volume->setGeometry(QRect(240, 10, 61, 61));
        dial_master_volume->setStyleSheet(QString::fromUtf8("background-color: lightgray"));
        dial_master_volume->setMaximum(1000);
        dial_master_volume->setValue(1000);
        dial_tempo = new QDial(groupBox_master_controls);
        dial_tempo->setObjectName(QString::fromUtf8("dial_tempo"));
        dial_tempo->setGeometry(QRect(350, 10, 61, 61));
        dial_tempo->setStyleSheet(QString::fromUtf8("background-color: mediumaquamarine"));
        dial_tempo->setMinimum(60);
        dial_tempo->setMaximum(180);
        dial_tempo->setValue(120);
        label_master_pitch = new QLabel(groupBox_master_controls);
        label_master_pitch->setObjectName(QString::fromUtf8("label_master_pitch"));
        label_master_pitch->setGeometry(QRect(15, 70, 71, 21));
        label_master_pitch->setStyleSheet(QString::fromUtf8("border: 1px solid black; background-color:lightblue;"));
        label_master_fm_amount = new QLabel(groupBox_master_controls);
        label_master_fm_amount->setObjectName(QString::fromUtf8("label_master_fm_amount"));
        label_master_fm_amount->setGeometry(QRect(120, 70, 81, 21));
        label_master_fm_amount->setStyleSheet(QString::fromUtf8("border: 1px solid black; background-color:pink;"));
        label_master_volume = new QLabel(groupBox_master_controls);
        label_master_volume->setObjectName(QString::fromUtf8("label_master_volume"));
        label_master_volume->setGeometry(QRect(230, 70, 81, 21));
        label_master_volume->setStyleSheet(QString::fromUtf8("border: 1px solid black; background-color:lightgray;"));
        label_master_volume_2 = new QLabel(groupBox_master_controls);
        label_master_volume_2->setObjectName(QString::fromUtf8("label_master_volume_2"));
        label_master_volume_2->setGeometry(QRect(340, 70, 81, 21));
        label_master_volume_2->setStyleSheet(QString::fromUtf8("border: 1px solid black; background-color: mediumaquamarine"));
        groupBox = new QGroupBox(centralwidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(0, 3, 471, 631));
        groupBox->setStyleSheet(QString::fromUtf8("background-color: #404040; border-radius: 10; border: 5px solid black"));
        MainWindow->setCentralWidget(centralwidget);
        groupBox->raise();
        groupBox_1->raise();
        groupBox_labels->raise();
        groupBox_4->raise();
        groupBox_5->raise();
        groupBox_6->raise();
        groupBox_7->raise();
        groupBox_8->raise();
        groupBox_2->raise();
        groupBox_3->raise();
        groupBox_master_controls->raise();

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        groupBox_1->setTitle(QString());
        btn_step_1->setText(QString());
        btn_step_9->setText(QString());
        groupBox_labels->setTitle(QString());
        label_pitch->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">PITCH</span></p></body></html>", nullptr));
        label_ramp->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">RAMP</span></p></body></html>", nullptr));
        label_ramp_decay->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">DECAY</span></p></body></html>", nullptr));
        label_fm_amount->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">FM</span></p></body></html>", nullptr));
        label_fm_frequency->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">FREQ</span></p></body></html>", nullptr));
        label_fm_decay->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">DECAY</span></p></body></html>", nullptr));
        label_fm_feedback->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">FB</span></p></body></html>", nullptr));
        label_aeg->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">AEG</span></p></body></html>", nullptr));
        label_volume->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">VOLUME</span></p></body></html>", nullptr));
        label_volume_2->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">STEPS</span></p></body></html>", nullptr));
        groupBox_4->setTitle(QString());
        btn_step_4->setText(QString());
        btn_step_12->setText(QString());
        groupBox_5->setTitle(QString());
        btn_step_5->setText(QString());
        btn_step_13->setText(QString());
        groupBox_6->setTitle(QString());
        btn_step_6->setText(QString());
        btn_step_14->setText(QString());
        groupBox_7->setTitle(QString());
        btn_step_7->setText(QString());
        btn_step_15->setText(QString());
        groupBox_8->setTitle(QString());
        btn_step_8->setText(QString());
        btn_step_16->setText(QString());
        groupBox_2->setTitle(QString());
        btn_step_2->setText(QString());
        btn_step_10->setText(QString());
        groupBox_3->setTitle(QString());
        btn_step_3->setText(QString());
        btn_step_11->setText(QString());
        groupBox_master_controls->setTitle(QString());
#ifndef QT_NO_TOOLTIP
        dial_master_fm_amount->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        label_master_pitch->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">PITCH</span></p></body></html>", nullptr));
        label_master_fm_amount->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">FM</span></p></body></html>", nullptr));
        label_master_volume->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">VOLUME</span></p></body></html>", nullptr));
        label_master_volume_2->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">TEMPO</span></p></body></html>", nullptr));
        groupBox->setTitle(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
